package edu.au.cpsc.inventory.partspecification.databaseaccess;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

/**
 * I am a database interaction session.  I keep a (JDBC) connection to the database and provide an
 * API for operations against that connection.
 */
public class Session {

  private Connection connection;

  public Session(Connection connection) throws SQLException {
    this.connection = connection;
    this.connection.setAutoCommit(false);
  }

  public PreparedStatement prepareStatement(String s, int autoGeneratedKeys) throws SQLException {
    return connection.prepareStatement(s, autoGeneratedKeys);
  }

  /**
   * Roll back the current transaction.
   */
  public void rollback() {
    try {
      connection.rollback();
    } catch (SQLException ex) {
      throw new DatabaseOperationFailed(ex);
    }
  }

  /**
   * Commit the current transaction.
   */
  public void commit() {
    try {
      connection.commit();
    } catch (SQLException ex) {
      throw new DatabaseOperationFailed(ex);
    }
  }
}
