package edu.au.cpsc.inventory.partspecification;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class Session {

  private Connection connection;

  public Session(Connection connection) throws SQLException {
    this.connection = connection;
    this.connection.setAutoCommit(false);
  }

  public PreparedStatement prepareStatement(String s, int autoGeneratedKeys) throws SQLException {
    return connection.prepareStatement(s, autoGeneratedKeys);
  }

  public void rollback() throws SQLException {
    connection.rollback();
  }
}
