package edu.au.cpsc.inventory.partspecification.dataaccess;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;

public class Session {

  private Connection connection;

  public Session(Connection connection) throws SQLException {
    this.connection = connection;
    this.connection.setAutoCommit(false);
  }

  public PreparedStatement prepareStatement(String s, int autoGeneratedKeys) throws SQLException {
    return connection.prepareStatement(s, autoGeneratedKeys);
  }

  public void rollback() {
    try {
      connection.rollback();
    } catch (SQLException ex) {
      throw new DatabaseOperationFailed(ex);
    }
  }

  public void commit() {
    try {
      connection.commit();
    } catch (SQLException ex) {
      throw new DatabaseOperationFailed(ex);
    }
  }
}
